import Image from "next/image";
import { BrandCover } from "@/components/brand";
import { site } from "@/config/site";
import { Eyebrow, TrialSection } from "@/components/ui";
import { pageMetadata } from "@/lib/metadata";
export const metadata = pageMetadata("Meet Shila", "Meet Shila Nepali, the person building Sushi Pilates in Kathmandu. Discover a thoughtful, welcoming approach to movement.", "/about");
export default function About() {
  return <><section className="page-heading container"><Eyebrow>A PERSON. A PRACTICE. A NEW BEGINNING.</Eyebrow><h1>Movement with meaning.<br /><em>Meet Shila.</em></h1><p>Building a space to move, connect, and feel a little more like yourself.</p></section><BrandCover /><section className="container instructor-section about-intro"><div className="instructor-image"><Image src={site.instructor.image} alt={site.instructor.imageAlt} fill sizes="(max-width: 760px) 90vw, 42vw" preload /><span className="image-caption">Shila’s portrait is coming soon</span></div><div className="instructor-copy"><Eyebrow>SHILA NEPALI · FOUNDER</Eyebrow><h2>A thoughtful start.<br /><em>An evolving journey.</em></h2><p>{site.instructor.introduction}</p><h3>Her Pilates journey</h3><p>{site.instructor.journey}</p><div className="signature">Shila Nepali</div></div></section><section className="section philosophy"><div className="container"><Eyebrow>OUR TEACHING PHILOSOPHY</Eyebrow><h2>Listen to your body.<br /><em>Let your practice grow.</em></h2><p>{site.instructor.philosophy}</p><p>The intention behind Sushi Pilates is simple: thoughtful guidance, an unhurried approach, and movement that fits into real life.</p></div></section><section className="section container"><Eyebrow>A SPACE FOR YOU</Eyebrow><h2>What you can expect.</h2><div className="expectations"><article><span>01</span><h3>A welcoming beginning</h3><p>Room for your questions, whether this is your first time exploring Pilates or you’re returning to movement.</p></article><article><span>02</span><h3>Intentional movement</h3><p>A focus on breath, control, and awareness, with time to understand the foundations.</p></article><article><span>03</span><h3>A practice at your pace</h3><p>Encouragement to notice your own progress and build a sustainable relationship with movement.</p></article></div></section><TrialSection /></>;
}
